services:
  - type: web
    name: operaciones-microfrontend
    env: static
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: .
