services:
  - type: web
    name: operaciones-microfrontend
    env: static
    buildCommand: npm install
    startCommand: npx serve -s . -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: .
